#
# gitlab-ci configuration file
#

stages:
  - build
  - deploy
  
build:
  variables:
    CI_REGISTRY: 'git.coinsane.space:4567'
  stage: build
  script:
    - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG"
  when: manual

deploy:
  stage: deploy
  script:
    - export > .env
    - scp .env ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_HOST}:/tmp/
    - ssh ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_HOST} 'docker login -u '"gitlab-ci-token"' -p '"$CI_BUILD_TOKEN"' '"$CI_REGISTRY"' '
    - ssh ${DEPLOYMENT_SERVER_USER}@${DEPLOYMENT_SERVER_HOST} 'docker pull '"$CI_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG"' '
  when: manual