#
# gitlab-ci configuration file
#

stages:
  - build
  
build:
  variables:
    CI_REGISTRY: '127.0.0.1:4567'
  stage: build
  script:
    - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG"
  when: manual
  allow_failure: true
