const mongoose = require('mongoose');

const marketSchema = new mongoose.Schema({
  id: String,
  imageUrl: String,
  name: String,
  order: Number,
  symbol: String,
  prices: {
    BTC: {
      price: Number,
      lastUpdate: Number,
      lastVolume: Number,
      lastVolumeTo: Number,
      volumeDay: Number,
      volumeDayTo: Number,
      volume24H: Number,
      volume24HTo: Number,
      openDay: Number,
      highDay: Number,
      lowDay: Number,
      open24H: Number,
      high24H: Number,
      low24H: Number,
      change24H: Number,
      changePct24H: Number,
      changeDay: Number,
      changePctDay: Number,
      supply: Number,
      marketCap: Number,
      totalVolume24H: Number,
      totalVolume24HTo: Number,
    },
    USD: {
      price: Number,
      lastUpdate: Number,
      lastVolume: Number,
      lastVolumeTo: Number,
      volumeDay: Number,
      volumeDayTo: Number,
      volume24H: Number,
      volume24HTo: Number,
      openDay: Number,
      highDay: Number,
      lowDay: Number,
      open24H: Number,
      high24H: Number,
      low24H: Number,
      change24H: Number,
      changePct24H: Number,
      changeDay: Number,
      changePctDay: Number,
      supply: Number,
      marketCap: Number,
      totalVolume24H: Number,
      totalVolume24HTo: Number,
    },
    RUB: {
      price: Number,
      lastUpdate: Number,
      lastVolume: Number,
      lastVolumeTo: Number,
      volumeDay: Number,
      volumeDayTo: Number,
      volume24H: Number,
      volume24HTo: Number,
      openDay: Number,
      highDay: Number,
      lowDay: Number,
      open24H: Number,
      high24H: Number,
      low24H: Number,
      change24H: Number,
      changePct24H: Number,
      changeDay: Number,
      changePctDay: Number,
      supply: Number,
      marketCap: Number,
      totalVolume24H: Number,
      totalVolume24HTo: Number,
    },
  },
  lastUpdated: { type: Date, default: Date.now },
  created: { type: Date, default: Date.now },
});

marketSchema.pre('save', function(next) {
  this.lastUpdated = Date.now();
  next();
});

module.exports = mongoose.model('Market', marketSchema);
